### ISSUE TITLE
Why is `Connection` a newtype?

### ISSUE THREAD

**Issue by hdgarrood** [zudov/purescript-websocket-simple#6]
Given that it has no instances, why not make it a type synonym? Currently you have to unpack it whenever you want to use it.

**Comment by zudov** [comment]
You are right, I now can't see why it had to be a `newtype`.

Do you have something to add to https://github.com/zudov/purescript-websocket-simple/pull/7 ?

**Comment by zudov** [comment]
I think I've recalled my original intention for using a `newtype` :sparkles:

Just aliasing `Connection` to anonymous record (quite a big one) might be not very convenient when it would pop up in error messages since printing the record would be quite noisy. That of course wouldn't give you any good after you unwrap it, for example:

``` haskell
do Connection socket <- ...
   socket.nonExistingProperty $= ...
```

would still result into the whole record printed, however if you define a function that accepts a `Connection`, newtype would substantially improve the error message:   

``` haskell
makeUseOfConnection :: AppConfig -> Connection -> Eff _ Unit
makeUseOfConnection connection config = do -- bindings are erroneously swapped
  Connection socket <- connection
```

Should result into something like "Couldn't match `AppConfig` with `Connection`" instead of "Couldn't match `AppConfig` with `{ onMessage :: ..., onConnect :: ..., ......... }`"

I am not sure if I still want to have linked PR merged, however I think it could be nice to properly hide the implementation of `Connection` providing the accessors instead of exposing the constructors as @hdgarrood proposed in that PR.

**Comment by hdgarrood** [comment]
Ah, of course, that's a good point. I am also leaning towards the approach with hiding the constructors and exposing accessor functions. :)

**Comment by zudov** [comment]
Sometimes it's good to take things slow :)
